### ISSUE TITLE
How to fail when linter doesn't pass?

### ISSUE THREAD

**Issue by alexreinking** [julianwachholz/flake8-action#12]
When linter annotations are added, the check still succeeds, allowing a merge and not clearly marking that there even are annotations added. How can I make the check fail?

**Comment by julianwachholz** [comment]
Thank you for bringing this up! This was an issue with the check always running with the test flag. Should be fixed now with https://github.com/julianwachholz/flake8-action/commit/ad9f9dbe7d2602ffb320e96355b257ee7c4dbb85

Could you please check again by running against the latest version? (`@master`)

**Comment by FirefoxMetzger** [comment]
The test is still always passing for me. I tried it with `isTest=true`, `isTest=false`, and accidentally with `isTest=True`.

Here is the action

```yaml
  style:
    name: "Linting"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          args: ". --check"
      - name: Flake8
        uses: julianwachholz/flake8-action@v1.1.0
        with:
          checkName: "Linting"
          isTest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I'm also not seeing any annotations in the PR :( I guess I have something else misspecified?
