### ISSUE TITLE
how to add flake8 plugins 

### ISSUE THREAD

**Issue by elisim** [julianwachholz/flake8-action#22]
Hi,

Thank you for the great action!
I would like to use flake8 additional plugins (e.g. [pep8-naming](https://github.com/PyCQA/pep8-naming)). 

How should I do it using the action?

I saw this line in the source code
https://github.com/julianwachholz/flake8-action/blob/a61bd56b820b13d9aba277ae84ebbbebccd4a092/dist/index.js#L17

It seems to me that it could be inserted there, but I'm not sure.

Thank you,
Eli

**Comment by julianwachholz** [comment]
Thanks for the suggestion! The plugins can now be specified.

**Comment by elisim** [comment]
Thank you!

Strangely, now when running the action on pull_request, the build is passing even if the linting failed. Log:

![image](https://user-images.githubusercontent.com/17675462/134516367-fd3467cb-7417-40f7-844c-9a8f4ad8aa7f.png)

My .yaml file:

```yaml
# Based on https://github.com/julianwachholz/flake8-action

name: Code Quality

on:
  pull_request:
#    paths:
#      - '*.py'
    branches:
      - main
      - develop

jobs:
  lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
          path: .
          plugins: "pep8-naming==0.12.1 flake8-comprehensions==3.6.1"
          config: .flake8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I took insipration from your yaml file [here](https://github.com/julianwachholz/flake8-action-test/pull/1/checks?check_run_id=3640082376), and the only difference that I spot was on push (your code) whereas in mine is on pull_request.

What do you think?


BTW: consider adding in the README.md how to add multiple plugins: `plugins: "pep8-naming==0.12.1 flake8-comprehensions==3.6.1"`
